### ISSUE TITLE
Lowercase "a" is different between normal font and italic

### ISSUE THREAD

**Issue by cbraga9** [JulietaUla/Montserrat#132] opened 2022-07-21 16:19 UTC
![image](https://user-images.githubusercontent.com/10410099/180263571-0d33b0cb-2167-4407-aa9b-2e4d0963d3dc.png)
![image](https://user-images.githubusercontent.com/10410099/180263876-83e5c491-46c3-4479-afaf-0f183d8b8508.png)

The italic variant of the letter "a" is different to the normal variant.

**Comment by kenmcd** [comment] 2022-07-21 21:31
That is by design, so I do not think that is going to change.
But you do have a couple options.
You can apply stylistic set 01 (`ss01`) to Regular to get the same single-storey `a`.
![Montserrat-Regular-SS01](https://user-images.githubusercontent.com/844920/180316932-486397a3-3ccc-4aae-9b30-4c3bad0799f9.png)
Or you can apply stylistic set 01 (`ss01`) to Italic to get a different `a`.
![Montserrat-Italic-SS01](https://user-images.githubusercontent.com/844920/180317120-2dc4a257-9676-4f4b-985b-59e1d011d3da.png)

Or you can do both.
As you can see `ss01` also affects other characters such as the `l` and `t`.
So you may want to apply it to just the `a` if desired.

**Comment by juandelperal** [comment] 2023-11-08 09:49
Hi there. Yes, that's how the design is indeed. 
We are closing this issue, thanks

**Closed by juandelperal** 2023-11-08 09:49 UTC

**Comment by cssobral2013** [comment] 2023-12-08 22:23
@cbraga9 - As a sidenote, if you want multiplexed posture in Montserrat, please see my fork of Montserrat: https://github.com/cssobral2013/argentum-sans
