### ISSUE TITLE
czech characters render slightly lower than others on linux

### ISSUE THREAD

**Issue by Pr0b** [JulietaUla/Montserrat#67] opened 2018-02-22 13:30 UTC
czech characters render slightly lower than others on OS gnu/linux

font:
`<link` href="https://fonts.googleapis.com/css?family=Montserrat&amp;subset=latin-ext" rel="stylesheet">

css:
```
font-family: 'Montserrat', sans-serif;
font-weight: 400;
font-size: 1.25em;
```
text:
1 stroužek `česneku`

result:
![screenshot-2018-2-22 bearinkitchenui](https://user-images.githubusercontent.com/3258823/36540893-65130180-17dc-11e8-8488-ac688661733e.png)
Here's a [jsfiddle](https://jsfiddle.net/toa6tbjv/1/)

**Comment by alerque** [comment] 2018-02-22 15:26
I am not seeing this result even in your Fiddle. I'm on Archlinux with Firefox.

Here is your fiddle: 
![selection_042](https://user-images.githubusercontent.com/173595/36546944-af57cfd4-17fd-11e8-93a8-81e99ae86e01.png)

Here is the same fiddle with the string from your issue:
![selection_043](https://user-images.githubusercontent.com/173595/36546995-ca7092ce-17fd-11e8-8ede-3331e5291b39.png)

Both look fine to me. What browser are you using?

**Comment by Pr0b** [comment] 2018-02-22 15:48
i've got same result with 
* firefox - 58.0.2 (64-bit)
* google-chrome - Version 64.0.3282.167 (Official Build) (64-bit)

So it seems it's not web browser dependent.

I am also using Arch
Linux rob-pc 4.15.3-2-ARCH #1 SMP PREEMPT x86_64 GNU/Linux

But I didn't change default font settings on this machine.
I reproduced it on 2 independent Arch installations so far.

**Comment by alerque** [comment] 2018-02-22 16:41
The kernel version isn't going to be important here. Is your Arch system up to date with all packages? What DE are you using? What versions of fontconfig & harfbuzz do you have? Are you sure you don't have something else interfering?

**Comment by alerque** [comment] 2018-02-22 19:40
Okay I have more ideas. The Google Fonts style sheet in your jsfiddle actually looks on your system first, then loads from Google Fonts. So we might not be loading the same font files. Here's the magic question: do you have the Montserrat packages installed on Archlinux from the AUR, have you manually installed the font some other way, or are you getting the Google Fonts hosted version?

My systems have the latest `otf-montserrat` and `ttf-montserrat` packages with the 7.200 release of the font installed from the AUR (I am actually the maintainer of those packages). What I don't know is whether my browser is prioritizing the OTF or TTF version. This bug might be a difference between those two. Or it could be that _you_ are using some other version of the font. What font files and version are you actually loading?

**Comment by alerque** [comment] 2018-02-23 09:33
Okay now we're getting somewhere. So the problem is not with the font itself (the released 7.200 version is fine for both of us) but with the specific builds of it hosted by Google Fonts, which are apparently not the same as what's on Github. I suspect something is different between their Latin & Latin Extended range builds, and since those are loading from two different files there is some kind of missmatch going on. One or both probably needs rebuilding to be a match.

@davelab6 this is sounding like something up your alley no?

**Comment by Samuell1** [comment] 2019-05-10 07:32
Same issue for me latin-ext is broken for some characters like `č` or `ť` on google fonts but if i set font-weight 300 it magically works.

(first row 400 and second is 300 weight)
![obrázok](https://user-images.githubusercontent.com/3110002/57510176-63085800-7306-11e9-99a4-d530032d0b4a.png)

**Comment by juandelperal** [comment] 2019-05-10 11:30
@Samuell1 it seems that the regular font you are viewing in the first line is a local old version installed on your system.

Check out
https://jsfiddle.net/7g3tusmy/4/

it renders:
<img width="381" alt="Screen Shot 2019-05-10 at 8 29 29 AM" src="https://user-images.githubusercontent.com/2414972/57524297-c8a41680-72fd-11e9-93ea-4c4f31aaac86.png">

**Comment by Samuell1** [comment] 2019-05-10 12:02
@juandelperal Thanks! Thats was the issue.

**Comment by alerque** [comment] 2019-05-10 13:58
This issue can be closed. It is fixed in both the font itself and the version on Google Fonts. The only instances of it are people that have an older version on their system and think they are using Google Fonts and actually seeing outdated versions from their own system.

If anybody is watching this issue tracker can you please close this issue. Thanks.

**Closed** 2019-05-10 14:00 UTC
